import type { ReactNode } from "react";
import { useDashboard, useMonitor } from "@/store/monitor";
import { money, units } from "@/lib/engine/time";

function Formula({ children }: { children: ReactNode }) { return <div className="mt-2 overflow-x-auto rounded-lg border border-border bg-background px-4 py-3 font-mono text-sm leading-7 whitespace-pre-line">{children}</div>; }
function Calc({ children, centered = false }: { children: ReactNode; centered?: boolean }) { return <div className={`mt-2 rounded-lg bg-black/10 px-4 py-3 text-sm tabular-nums text-muted ${centered ? "text-center" : ""}`}><span className="mr-2 text-xs font-semibold uppercase tracking-wider text-subtle">Live calculation</span>{children}</div>; }
function Section({ title, source, children }: { title: string; source?: string; children: ReactNode }) { return <section className="rounded-2xl bg-elevated p-5 shadow-border sm:p-6"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="font-display text-xl font-medium">{title}</h2>{source ? <code className="text-xs text-subtle">{source}</code> : null}</div>{children}</section>; }
function Row({ name, formula, calculation, note }: { name: string; formula: string; calculation?: ReactNode; note?: string }) { return <div className="border-t border-border py-4 first:border-t-0"><p className="font-medium">{name}</p><Formula>{formula}</Formula>{calculation ? <Calc>{calculation}</Calc> : null}{note ? <p className="mt-2 text-sm text-muted">{note}</p> : null}</div>; }
function MeterPair({ meter1, meter2 }: { meter1: ReactNode; meter2: ReactNode }) { return <div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-meter1">Meter 1</p><div className="mt-2 text-sm tabular-nums">{meter1}</div></div><div className="rounded-xl border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-meter2">Meter 2</p><div className="mt-2 text-sm tabular-nums">{meter2}</div></div></div>; }

export function RefView() {
  const gs = useMonitor((s) => s.general);
  const t1 = useMonitor((s) => s.tariff1);
  const t2 = useMonitor((s) => s.tariff2);
  const { dashboard } = useDashboard();
  const slabs = (t: typeof t1) => t.consumerType === "Protected" ? t.protectedSlabs : t.slabs;

  if (dashboard.empty) return <div className="rounded-2xl bg-elevated p-10 text-center shadow-border"><p className="font-display text-xl">{dashboard.message}</p></div>;
  const d = dashboard;
  const b1 = Number(d.billingNew || 0);
  const b2 = Number(d.billingOld || 0);
  const total = Number(d.billingTotal || 0);
  const carry1 = Number(d.carryForwardNew || 0);
  const carry2 = Number(d.carryForwardOld || 0);
  const carry = carry1 + carry2;
  const projected = Number(d.projectedTotal || 0);
  const future = Number(d.projection.futureTotal || 0);
  const rolling = Number(d.projection.rolling15Average || 0);
  const remaining = Number(d.projection.remainingDays || 0);
  const actualBill1 = Number(d.currentBillNew || 0);
  const actualBill2 = Number(d.currentBillOld || 0);
  const projectedBill = Number(d.projectedBillActualTotal || 0);

  return <div className="space-y-5">
    <section className="rounded-2xl bg-foreground p-5 text-background shadow-border sm:p-6"><p className="text-xs font-medium uppercase tracking-wider opacity-60">Calculation reference</p><h1 className="mt-1 font-display text-3xl font-medium tracking-tight">Ref</h1><p className="mt-2 max-w-3xl text-sm opacity-75">Every formula below is followed by its current live calculation from the same dashboard state. Meter-specific calculations are separated; shared calculations are centered.</p></section>

    <Section title="1. Reading normalization" source="engine/readings.ts"><Row name="Carry-forward" formula="Blank meter input → previous normalized reading" calculation={<MeterPair meter1={<>Current reading: {units(d.currentNew)}; starting reading: {units(d.initialNew)}</>} meter2={<>Current reading: {units(d.currentOld)}; starting reading: {units(d.initialOld)}</>} />} /><Row name="Consumption difference" formula="Δ = endReading − startReading\nnegative Δ → unavailable" calculation={<MeterPair meter1={<>{units(d.currentNew)} − {units(d.initialNew)} = {units(b1)} kWh</>} meter2={<>{units(d.currentOld)} − {units(d.initialOld)} = {units(b2)} kWh</>} />} /><Row name="Combined current-period consumption" formula="Total = Δ₁ + Δ₂" calculation={<Calc centered>{units(b1)} + {units(b2)} = {units(total)} kWh</Calc>} /></Section>

    <Section title="2. Reading interpolation" source="engine/readings.ts + engine/time.ts"><Row name="Profile-weighted interpolation" formula="estimatedReading = before + (after − before) × W(before,target) / W(before,after)" calculation={<Calc centered>Applied to readings crossing a calculation boundary; current period usage resolves to {units(total)} kWh.</Calc>} /><Row name="Profile weight" formula="W(a,b) = Σ(profileWeight(hour) × minutes in hour)" calculation={<Calc centered>Configured estimation profile: solar/daytime {String(gs.solarStartHour).padStart(2, "0")}:{String(gs.solarStartMinute).padStart(2, "0")} → {String(gs.solarEndHour).padStart(2, "0")}:{String(gs.solarEndMinute).padStart(2, "0")}.</Calc>} /></Section>

    <Section title="3. Billing period and daily time model" source="engine/time.ts"><Row name="Billing period" formula="Start = configured billing boundary\nEnd = Start + 1 calendar month" calculation={<Calc centered>{d.billingStart} → {d.billingEnd} · {units(d.elapsedDays, 1)} elapsed days of the selected period.</Calc>} /><Row name="Daily period" formula="Day start = configured billing clock\nDay end = Day start + 1 day" calculation={<Calc centered>{String(gs.billingHour).padStart(2, "0")}:{String(gs.billingMinute).padStart(2, "0")} → next day at the same time.</Calc>} /><Row name="Billing progress" formula="Progress = elapsedDays / periodDays × 100%" calculation={<Calc centered>{Number(d.billingProgress).toFixed(2)}% of the current billing period.</Calc>} /></Section>

    <Section title="4. Daily consumption" source="engine/dashboard.ts"><Row name="Completed day" formula="Daily total = Meter 1 daily consumption + Meter 2 daily consumption" calculation={<Calc centered>Latest available daily periods are built from the same interpolated meter readings; the current-period total is {units(total)} kWh.</Calc>} /><Row name="Current/incomplete day" formula="Incomplete day is expanded with the configured profile when required" calculation={<Calc centered>Projection uses completed 5pm-to-5pm periods for the rolling average; incomplete current-day data is not treated as one of the 15 completed days.</Calc>} /></Section>

    <Section title="5. Daily average and goal pace" source="engine/dashboard.ts"><Row name="Daily average" formula="Daily average = Current-period units / elapsed days" calculation={<Calc centered>{units(total)} ÷ {units(d.elapsedDays, 1)} = {units(d.goalPace.dailyAverage)} kWh/d</Calc>} /><Row name="Target daily average" formula="Target = Goal / full billing-period days" calculation={<Calc centered>{units(d.goalPace.goal)} ÷ {units(d.goalPace.elapsedDays + d.goalPace.remainingDays, 1)} = {units(d.goalPace.targetDailyAverage)} kWh/d</Calc>} /><Row name="Remaining to goal" formula="Remaining = Goal − current-period units" calculation={<Calc centered>{units(d.goalPace.goal)} − {units(total)} = {units(d.goalPace.remainingUnits)} kWh</Calc>} /><Row name="Required daily average" formula="Required = Remaining / remaining days" calculation={<Calc centered>{d.goalPace.requiredDailyAverage === "" ? "Not defined" : `${units(d.goalPace.remainingUnits)} ÷ ${units(d.goalPace.remainingDays, 1)} = ${units(d.goalPace.requiredDailyAverage)} kWh/d`}</Calc>} /></Section>

    <Section title="6. Active days per meter" source="engine/dashboard.ts"><Row name="Meter activity" formula="Positive register movement assigns the interval to that meter; ambiguous simultaneous movement is split proportionally." calculation={<MeterPair meter1={<>Active days: {units(d.activeDaysNew, 1)}</>} meter2={<>Active days: {units(d.activeDaysOld, 1)}</>} />} /><Row name="Meter daily average" formula="Meter average = meter current-period consumption / meter active days" calculation={<MeterPair meter1={<>{units(b1)} ÷ {units(d.activeDaysNew, 1)} = {units(d.averageNew)} kWh/d</>} meter2={<>{units(b2)} ÷ {units(d.activeDaysOld, 1)} = {units(d.averageOld)} kWh/d</>} />} /></Section>

    <Section title="7. Month projection" source="engine/dashboard.ts"><Row name="Rolling 15-day average" formula="Rolling average = Σ(last 15 completed daily totals) / number of completed daily totals" calculation={<Calc centered>{units(d.projection.rolling15Total)} ÷ {units(d.projection.rolling15Days, 0)} = {units(rolling)} kWh/d</Calc>} note="The average is combined across Meter 1 and Meter 2. It does not depend on which meter was active on each day." /><Row name="Future consumption" formula="Future = Rolling 15-day average × remaining billing-period days" calculation={<Calc centered>{units(rolling)} × {units(remaining, 1)} = {units(future)} kWh</Calc>} /><Row name="Projected month" formula="Projected total = current-period consumption + future consumption" calculation={<Calc centered>{units(total)} + {units(future)} = {units(projected)} kWh</Calc>} /><Row name="Meter-specific projection allocation" formula="Future units are allocated only for meter-specific bill estimation; projected total remains the combined rolling-average projection." calculation={<MeterPair meter1={<>{units(d.projection.actualNew)} current + {units(d.projection.futureNew)} future = {units(d.projection.newMeter)} kWh</>} meter2={<>{units(d.projection.actualOld)} current + {units(d.projection.futureOld)} future = {units(d.projection.oldMeter)} kWh</>} />} /></Section>

    <Section title="8. Carry-forward and pro-rata adjustment" source="engine/dashboard.ts + engine/bill.ts"><Row name="Carry-forward" formula="Carry-forward = actual interval units − pro-rata adjusted billed units" calculation={<MeterPair meter1={<>{units(carry1)} kWh carried from the previous month; excluded from the current-period usage total.</>} meter2={<>{units(carry2)} kWh carried from the previous month; excluded from the current-period usage total.</>} />} /><Row name="Current usage versus carry-forward" formula="Displayed current-period units do not include carry-forward; carry-forward is retained separately for billing adjustment." calculation={<Calc centered>{units(total)} kWh current-period usage + {units(carry)} kWh separate carry-forward.</Calc>} /></Section>

    <Section title="9. Meter bill calculation" source="engine/bill.ts"><Row name="Applicable slab" formula="Select slab independently for each meter from that meter's total billable units" calculation={<MeterPair meter1={<>Current bill: {money(actualBill1)}</>} meter2={<>Current bill: {money(actualBill2)}</>} />} /><Row name="Energy, adjustments and taxes" formula="Energy = Units × rate\nAdjustments = Units × (FCA + QTA + FC + NJ)\nDuty/GST/fixed charges are then applied per tariff." calculation={<MeterPair meter1={<>{units(b1 + carry1)} billable units → {money(actualBill1)}</>} meter2={<>{units(b2 + carry2)} billable units → {money(actualBill2)}</>} />} /><Row name="Combined bill" formula="Combined bill = Meter 1 bill + Meter 2 bill" calculation={<Calc centered>{money(actualBill1)} + {money(actualBill2)} = {money(actualBill1 + actualBill2)}</Calc>} /><Row name="Projected bill" formula="Projected bill = independently calculated Meter 1 projected bill + Meter 2 projected bill" calculation={<Calc centered>{money(projectedBill)} projected bill using the projected meter allocations.</Calc>} /></Section>

    <Section title="10. Current tariff inputs" source="settings"><div className="grid gap-4 sm:grid-cols-2">{[["Meter 1", t1], ["Meter 2", t2]].map(([name, t]) => <div key={name as string} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-medium">{name as string}</h3><span className="text-xs text-muted">{(t as typeof t1).slabMode}</span></div><p className="mt-1 text-sm text-muted">{(t as typeof t1).consumerType}</p><div className="mt-3 space-y-2">{slabs(t as typeof t1).map((s) => <div key={`${s.min}-${s.max}`} className="flex justify-between gap-3 border-t border-border pt-2 text-sm"><span>{s.max === Infinity ? `>${s.min - 1}` : `${s.min}–${s.max}`} units</span><span className="font-mono">Rs {Number(s.rate).toFixed(2)} · fixed Rs {Number(s.fixed).toFixed(2)}</span></div>)}</div><div className="mt-3 border-t border-border pt-3 text-xs text-muted">ED {(t as typeof t1).adjustments.ED}% · GST {(t as typeof t1).adjustments.GST}% · TV Rs {Number((t as typeof t1).adjustments.TV).toFixed(2)} · FCA {(t as typeof t1).adjustments.FCA} · QTA {(t as typeof t1).adjustments.QTA} · FC {(t as typeof t1).adjustments.FC} · NJ {(t as typeof t1).adjustments.NJ}</div></div>)}</div></Section>

    <Section title="11. Display calculations" source="summary-view.tsx"><Row name="Effective projected rate" formula="Effective rate = projected bill / projected month units" calculation={<Calc centered>{money(projectedBill)} ÷ {units(projected)} = Rs {(projected > 0 ? projectedBill / projected : 0).toFixed(2)}/kWh</Calc>} /><Row name="Meter split percentage" formula="Meter share = meter current-period units / combined current-period units × 100%" calculation={<MeterPair meter1={<>{units(b1)} ÷ {units(total)} = {Number(d.meter1Share || 0).toFixed(1)}%</>} meter2={<>{units(b2)} ÷ {units(total)} = {Number(d.meter2Share || 0).toFixed(1)}%</>} />} /><Row name="Total usage display" formula="Displayed total = Meter 1 current-period units + Meter 2 current-period units" calculation={<Calc centered>{units(b1)} + {units(b2)} = {units(total)} kWh</Calc>} /></Section>

    <Section title="12. Important calculation rules" source="current engine"><ul className="list-disc space-y-2 pl-5 text-sm text-muted"><li>Blank readings carry forward the previous reading.</li><li>Negative meter differences are unavailable rather than consumption.</li><li>Meter bills are calculated independently before being combined.</li><li>Carry-forward is displayed separately and is not included in the main current-period usage or projected-month units.</li><li>Future estimation uses the arithmetic mean of the last 15 completed 5pm-to-5pm daily totals, regardless of meter.</li><li>Only the future meter allocation used for billing needs a meter distinction; it does not change the combined projected usage.</li><li>This reference page mirrors the calculation engine and its live dashboard values.</li></ul></Section>
  </div>;
}
