import { UsageChart } from "@/components/charts/usage-chart";
import { useDashboard, useMonitor } from "@/store/monitor";
import { money, units, addMonth, getBillingPeriodStart } from "@/lib/engine/time";
import { applyCarryForward, interpolatedReadingsAt } from "@/lib/engine/readings";
import type { DailyPoint, HourlyProfilePoint, ReadingInput } from "@/lib/engine/types";
import { useEffect, useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

function Stat({ label, value, unit, hint }: { label: string; value: string; unit?: string; hint?: string }) {
  return <div><p className="text-xs font-medium uppercase tracking-wider text-muted">{label}</p><p className="mt-1 font-display text-xl font-medium tabular-nums text-foreground">{value}{unit ? <span className="ml-1 text-sm font-normal text-subtle">{unit}</span> : null}</p>{hint ? <p className="mt-0.5 text-xs text-subtle">{hint}</p> : null}</div>;
}

function MeterCard({ title, tone, billing, carry, average, activeDays, bill, current, initial }: { title: string; tone: "meter1" | "meter2"; billing: number | ""; carry: number; average: number | ""; activeDays: number; bill: number; current: number | null; initial: number | null }) {
  return <article className="rounded-xl bg-elevated p-5 shadow-border"><div className={`h-1 w-12 rounded-full ${tone === "meter1" ? "bg-meter1" : "bg-meter2"}`} /><p className="mt-3 text-xs font-medium uppercase tracking-wider text-muted">{title}</p><p className="mt-1 font-display text-3xl font-medium tabular-nums">{units(billing)} <span className="text-base text-subtle">kWh</span></p><p className="mt-1 text-xs text-subtle tabular-nums">+ {units(carry)} kWh carry-forward from last month</p><dl className="mt-4 grid grid-cols-2 gap-3 border-t border-border pt-4 text-sm"><div><dt className="text-xs text-muted">Daily average</dt><dd className="tabular-nums">{units(average)} <span className="text-xs font-normal text-subtle">kWh/d</span></dd><p className="mt-0.5 text-[11px] text-subtle">{units(activeDays, 1)} active days</p></div><div><dt className="text-xs text-muted">Bill to date</dt><dd className="tabular-nums">{money(bill)}</dd></div><div><dt className="text-xs text-muted">Latest reading</dt><dd className="tabular-nums">{units(current)}</dd></div><div><dt className="text-xs text-muted">Starting reading</dt><dd className="tabular-nums">{units(initial)}</dd></div></dl></article>;
}

type MeterSegment = { meter: "new" | "old"; start: number; end: number };
function billingMeterSegments(inputs: ReadingInput[], billingStart: Date, billingEnd: Date, visibleEnd: Date): MeterSegment[] {
  const end = Math.min(billingEnd.getTime(), visibleEnd.getTime()); const start = billingStart.getTime(); if (end <= start) return [];
  const readings = applyCarryForward([...inputs].sort((a, b) => a.datetime - b.datetime)); if (!readings.length) return [];
  const points = [{ datetime: start, ...interpolatedReadingsAt(readings, billingStart) }, ...readings.filter((r) => r.datetime > start && r.datetime < end), { datetime: end, ...interpolatedReadingsAt(readings, new Date(end)) }].sort((a, b) => a.datetime - b.datetime);
  let active: "new" | "old" | null = null; const segments: MeterSegment[] = [];
  const detectActive = (a: { newReading: number | null; oldReading: number | null }, b: { newReading: number | null; oldReading: number | null }) => { const newDelta = a.newReading == null || b.newReading == null ? 0 : Number(b.newReading) - Number(a.newReading); const oldDelta = a.oldReading == null || b.oldReading == null ? 0 : Number(b.oldReading) - Number(a.oldReading); if (newDelta > 0.0001 && oldDelta <= 0.0001) return "new" as const; if (oldDelta > 0.0001 && newDelta <= 0.0001) return "old" as const; if (newDelta > 0.0001 && oldDelta > 0.0001) return newDelta >= oldDelta ? "new" as const : "old" as const; return null; };
  let previous = readings[0]; for (const reading of readings) { if (reading.datetime > start) break; const detected = detectActive(previous, reading); if (detected) active = detected; previous = reading; }
  for (let i = 0; i < points.length - 1; i++) { const a = points[i], b = points[i + 1]; if (b.datetime <= a.datetime) continue; const detected = detectActive(a, b); if (detected) active = detected; if (!active) { if (a.newReading != null && a.oldReading == null) active = "new"; else if (a.oldReading != null && a.newReading == null) active = "old"; } if (!active) continue; const last = segments[segments.length - 1]; if (last && last.meter === active && last.end === a.datetime) last.end = b.datetime; else segments.push({ meter: active, start: a.datetime, end: b.datetime }); }
  return segments;
}
function themeColor(name: string, fallback: string) { if (typeof document === "undefined") return fallback; const v = getComputedStyle(document.documentElement).getPropertyValue(name).trim(); return v || fallback; }
function formatGraphTime(hour: number, minute: number) { const period = hour >= 12 ? "PM" : "AM"; const displayHour = hour % 12 || 12; return `${displayHour}${minute ? `:${String(minute).padStart(2, "0")}` : ""}${period}`; }
function HistoricalProfileChart({ profile }: { profile: HourlyProfilePoint[] }) {
  const [color, setColor] = useState("#E3B341"); useEffect(() => { setColor(themeColor("--color-profile", "#E3B341")); }, []); const data = profile.map((p) => ({ label: formatGraphTime(p.hour, p.minute), percent: p.percent }));
  return <div className="h-72 w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 16, right: 4, left: -18, bottom: 0 }}><CartesianGrid stroke={themeColor("--color-border", "#3a3c36")} vertical={false} /><XAxis dataKey="label" tick={{ fill: "var(--color-muted)", fontSize: 11 }} axisLine={false} tickLine={false} interval={1} /><YAxis tick={{ fill: "var(--color-muted)", fontSize: 11 }} axisLine={false} tickLine={false} width={40} tickFormatter={(value) => `${value}%`} /><Tooltip content={({ active, payload }) => { if (!active || !payload?.length) return null; const value = Number(payload.find((p) => p.dataKey === "percent")?.value ?? 0); const label = String(payload[0]?.payload?.label ?? ""); return <div className="rounded-lg border border-border bg-elevated px-3 py-2 text-xs shadow-border"><p className="mb-1 font-medium text-foreground">{label}</p><p className="text-profile">Historical profile · {units(value, 1)}%</p></div>; }} cursor={{ fill: "rgba(236,235,228,0.06)" }} /><Line type="monotone" dataKey="percent" stroke={color} strokeWidth={2.5} dot={false} activeDot={false} /></LineChart></ResponsiveContainer></div>;
}

export function SummaryView() {
  const { dashboard, hourlyProfile } = useDashboard(); const setHourlyDay = useMonitor((s) => s.setHourlyDay); const hourlyDay = useMonitor((s) => s.hourlyDay); const hourlyOverride = useMonitor((s) => s.hourlyOverride); const rawReadings = useMonitor((s) => s.readings); const general = useMonitor((s) => s.general); const selectedMonth = useMonitor((s) => s.selectedMonth);
  if (dashboard.empty) return <div className="rounded-2xl bg-elevated p-10 text-center shadow-border"><p className="font-display text-xl">{dashboard.message}</p></div>;
  const d = dashboard; const hourly = hourlyOverride ?? d.hourly; const pace = d.goalPace; const displayedUsage = Number(d.billingTotal || 0); const carryForward = Number(d.carryForwardNew || 0) + Number(d.carryForwardOld || 0); const projectedUsage = d.isCurrentBillingMonth ? Number(d.projectedTotal || 0) : displayedUsage; const displayedBill = d.isCurrentBillingMonth ? Number(d.projectedBillActualTotal || 0) : Number(d.currentBillNew || 0) + Number(d.currentBillOld || 0); const effectiveRate = projectedUsage > 0 ? displayedBill / projectedUsage : 0; const remainingFuture = Number(d.projection?.futureTotal || 0);
  const billingStart = selectedMonth ? new Date(Number(selectedMonth)) : getBillingPeriodStart(new Date(), general); const billingEnd = addMonth(billingStart); const visibleEnd = d.isCurrentBillingMonth ? new Date() : billingEnd; const meterSegments = billingMeterSegments(rawReadings, billingStart, billingEnd, visibleEnd); const progressStart = billingStart.getTime(); const progressSpan = Math.max(1, billingEnd.getTime() - progressStart); const activeMeter = meterSegments.length ? meterSegments[meterSegments.length - 1].meter : null; const startMeter = meterSegments.length ? meterSegments[0].meter : "new"; const activeMeterLabel = activeMeter === "new" ? "Meter 1" : activeMeter === "old" ? "Meter 2" : "";
  const projectionProgress = projectedUsage > 0 ? Math.min(100, (displayedUsage / projectedUsage) * 100) : 0;

  return <div className="space-y-5">
    <section className="rounded-2xl bg-elevated p-5 shadow-border sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-display text-3xl font-medium tracking-tight text-balance">{d.billingMonth}</h2><p className="mt-1 text-sm text-muted">{d.billingStart} → {d.billingEnd}</p><p className="mt-1 text-xs text-subtle tabular-nums">Elapsed {units(d.elapsedDays, 1)} days</p></div><div className="text-right"><p className="text-sm font-medium tabular-nums text-muted">{Number(d.billingProgress).toFixed(0)}% of period</p>{activeMeterLabel ? <p className="mt-0.5 text-xs text-subtle">Active: {activeMeterLabel}</p> : null}</div></div><div className="relative mt-4 h-2 overflow-hidden rounded-full bg-muted">{meterSegments.map((segment, index) => { const left = ((segment.start - progressStart) / progressSpan) * 100; const width = ((segment.end - segment.start) / progressSpan) * 100; return <div key={`${segment.start}-${segment.end}-${index}`} className={`absolute inset-y-0 ${segment.meter === "new" ? "bg-meter1" : "bg-meter2"}`} style={{ left: `${Math.max(0, Math.min(100, left))}%`, width: `${Math.max(0, Math.min(100 - left, width))}%` }} />; })}</div><div className="mt-2 flex justify-between text-xs tabular-nums">{startMeter === "old" ? <><span className="text-meter2">Meter 2 · {units(d.billingOld)} kWh</span><span className="text-meter1">Meter 1 · {units(d.billingNew)} kWh</span></> : <><span className="text-meter1">Meter 1 · {units(d.billingNew)} kWh</span><span className="text-meter2">Meter 2 · {units(d.billingOld)} kWh</span></>}</div></section>
    <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-2xl bg-elevated p-5 shadow-border lg:col-span-2 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-wider text-muted">Total units consumed</p><p className="mt-1 font-display text-5xl font-medium tracking-tight tabular-nums sm:text-6xl">{units(displayedUsage)}<span className="ml-2 text-lg font-normal text-subtle">kWh</span></p><p className="mt-1 text-xs text-subtle tabular-nums">{units(carryForward)} kWh carry-forward from last month</p></div><div className="text-right"><p className="text-xs text-muted">Bill to date</p><p className="font-display text-2xl tabular-nums">{money(Number(d.currentBillNew || 0) + Number(d.currentBillOld || 0))}</p></div></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-border pt-5 sm:grid-cols-4"><Stat label="Last 24 hours" value={units(d.last24Total)} unit="kWh" /><Stat label="Daily average" value={units(pace.dailyAverage)} unit="kWh/d" /><Stat label="Remaining to goal" value={pace.remainingUnits > 0 ? units(pace.remainingUnits) : "Exceeded"} unit={pace.remainingUnits > 0 ? "kWh" : undefined} /><Stat label="Daily allowance" value={pace.requiredDailyAverage === "" ? pace.overGoal ? "Over" : "—" : units(pace.requiredDailyAverage)} unit={pace.requiredDailyAverage === "" ? undefined : "kWh/d"} /></div><p className="mt-4 text-pretty text-sm text-muted">{pace.overGoal ? `Combined goal exceeded by ${units(Math.abs(pace.remainingUnits))} kWh.` : `Stay at or below ${pace.requiredDailyAverage === "" ? "0" : units(pace.requiredDailyAverage)} kWh/d to finish on target.`}</p></section><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1">{startMeter === "old" ? <><MeterCard title="Meter 2" tone="meter2" billing={d.billingOld} carry={d.carryForwardOld} average={d.averageOld === "" ? "" : Number(d.averageOld)} activeDays={d.activeDaysOld} bill={d.currentBillOld} current={d.currentOld} initial={d.initialOld} /><MeterCard title="Meter 1" tone="meter1" billing={d.billingNew} carry={d.carryForwardNew} average={d.averageNew === "" ? "" : Number(d.averageNew)} activeDays={d.activeDaysNew} bill={d.currentBillNew} current={d.currentNew} initial={d.initialNew} /></> : <><MeterCard title="Meter 1" tone="meter1" billing={d.billingNew} carry={d.carryForwardNew} average={d.averageNew === "" ? "" : Number(d.averageNew)} activeDays={d.activeDaysNew} bill={d.currentBillNew} current={d.currentNew} initial={d.initialNew} /><MeterCard title="Meter 2" tone="meter2" billing={d.billingOld} carry={d.carryForwardOld} average={d.averageOld === "" ? "" : Number(d.averageOld)} activeDays={d.activeDaysOld} bill={d.currentBillOld} current={d.currentOld} initial={d.initialOld} /></>}</div></div>
    {d.isCurrentBillingMonth ? <section className="rounded-2xl bg-elevated p-5 shadow-border sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-wider text-muted">Estimated projection</p><h3 className="mt-1 font-display text-4xl font-medium tracking-tight tabular-nums sm:text-5xl">{units(projectedUsage)} <span className="text-lg font-normal text-subtle">kWh</span></h3><p className="mt-1 text-sm text-muted">Projected end-of-period consumption</p></div><div className="rounded-xl border border-border px-4 py-3 text-right"><p className="text-xs text-muted">Projected bill</p><p className="mt-1 font-display text-2xl tabular-nums">{money(displayedBill)}</p><p className="mt-0.5 text-xs text-subtle">{effectiveRate.toFixed(2)} Rs/kWh</p></div></div><div className="mt-5"><div className="flex justify-between text-xs tabular-nums text-muted"><span>Used {units(displayedUsage)} kWh</span><span>Future {units(remainingFuture)} kWh</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-foreground transition-[width] duration-300" style={{ width: `${projectionProgress}%` }} /></div></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-border pt-4 sm:grid-cols-4"><div><p className="text-xs text-muted">Daily pace</p><p className="mt-1 font-medium tabular-nums">{units(d.projection.rolling15Average)} <span className="text-xs font-normal text-subtle">kWh/d</span></p></div><div><p className="text-xs text-muted">Days averaged</p><p className="mt-1 font-medium tabular-nums">{units(d.projection.rolling15Days, 0)}</p></div><div><p className="text-xs text-muted">Days remaining</p><p className="mt-1 font-medium tabular-nums">{units(d.projection.remainingDays, 1)}</p></div><div><p className="text-xs text-muted">Calculation</p><p className="mt-1 font-medium tabular-nums">{units(displayedUsage)} + {units(remainingFuture)}</p></div></div></section> : null}
    <section className="rounded-2xl bg-elevated p-5 shadow-border sm:p-6"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-display text-lg font-medium">Daily consumption</h3><div className="flex items-center gap-3 text-xs text-muted"><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-sm bg-meter1" /> Meter 1</span><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-sm bg-meter2" /> Meter 2</span></div></div><UsageChart points={d.daily} onBarClick={(i) => { const point = d.daily[i] as DailyPoint | undefined; if (point) setHourlyDay(point.date); }} /></section>
    <section className="rounded-2xl bg-elevated p-5 shadow-border sm:p-6"><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-display text-lg font-medium">Hourly consumption</h3><p className="mt-1 text-xs text-subtle">Select a day to inspect its hourly consumption.</p></div><select value={hourlyDay} onChange={(e) => setHourlyDay(e.target.value)} className="h-11 rounded-md border border-border bg-surface px-3 text-sm">{d.hourlyDays.map((opt) => <option key={opt.value} value={opt.value}>{opt.label}</option>)}</select></div><div className="mb-2 flex items-center gap-4 text-xs text-muted"><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-meter1" /> Meter 1</span><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-meter2" /> Meter 2</span></div><UsageChart points={hourly} /></section>
    {hourlyProfile?.length ? <section className="rounded-2xl bg-elevated p-5 shadow-border sm:p-6"><div className="mb-3"><h3 className="font-display text-lg font-medium">Historical consumption profile</h3><p className="mt-1 text-xs text-subtle">Hourly distribution learned from completed days and weighted by the amount of actual reading data available for each day.</p></div><div className="mb-2 inline-flex items-center gap-1.5 text-xs text-muted"><span className="h-0.5 w-4 rounded bg-profile" /> Historical profile</div><HistoricalProfileChart profile={hourlyProfile} /></section> : null}
  </div>;
}
