/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _appRouteImport } from './routes/_app'
import { Route as _appIndexRouteImport } from './routes/_app/index'
import { Route as BillRouteImport } from './routes/_app/bill'
import { Route as HistoryRouteImport } from './routes/_app/history'
import { Route as NotesRouteImport } from './routes/_app/notes'
import { Route as SettingsRouteImport } from './routes/_app/settings'
import { Route as ReadingsRouteImport } from './routes/_app/readings'
import { Route as RefRouteImport } from './routes/_app/ref'
import { Route as HealthCheckRouteImport } from './routes/health-check'

const _appRoute = _appRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const _appIndexRoute = _appIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => _appRoute,
} as any)
const BillRoute = BillRouteImport.update({
  id: '/_app/bill',
  path: '/bill',
  getParentRoute: () => _appRoute,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/_app/history',
  path: '/history',
  getParentRoute: () => _appRoute,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/_app/notes',
  path: '/notes',
  getParentRoute: () => _appRoute,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/_app/settings',
  path: '/settings',
  getParentRoute: () => _appRoute,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/_app/readings',
  path: '/readings',
  getParentRoute: () => _appRoute,
} as any)
const RefRoute = RefRouteImport.update({
  id: '/_app/ref',
  path: '/ref',
  getParentRoute: () => _appRoute,
} as any)
const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => rootRouteImport,
} as any)

const _appRouteChildren = {
  _appIndexRoute: _appIndexRoute,
  BillRoute: BillRoute,
  HistoryRoute: HistoryRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  ReadingsRoute: ReadingsRoute,
  RefRoute: RefRoute,
}

export interface FileRoutesByFullPath {
  '/': typeof _appIndexRoute
  '/bill': typeof BillRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/readings': typeof ReadingsRoute
  '/ref': typeof RefRoute
  '/health-check': typeof HealthCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof _appIndexRoute
  '/bill': typeof BillRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/readings': typeof ReadingsRoute
  '/ref': typeof RefRoute
  '/health-check': typeof HealthCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof _appRoute
  '/_app/': typeof _appIndexRoute
  '/_app/bill': typeof BillRoute
  '/_app/history': typeof HistoryRoute
  '/_app/notes': typeof NotesRoute
  '/_app/settings': typeof SettingsRoute
  '/_app/readings': typeof ReadingsRoute
  '/_app/ref': typeof RefRoute
  '/health-check': typeof HealthCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bill' | '/history' | '/notes' | '/settings' | '/readings' | '/ref' | '/health-check'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bill' | '/history' | '/notes' | '/settings' | '/readings' | '/ref' | '/health-check'
  id: '__root__' | '/_app' | '/_app/' | '/_app/bill' | '/_app/history' | '/_app/notes' | '/_app/settings' | '/_app/readings' | '/_app/ref' | '/health-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _appRoute: typeof _appRoute
  HealthCheckRoute: typeof HealthCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _appIndexRouteImport
      parentRoute: typeof _appRoute
    }
    '/_app/bill': {
      id: '/_app/bill'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof BillRouteImport
      parentRoute: typeof _appRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof _appRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof _appRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof _appRoute
    }
    '/_app/readings': {
      id: '/_app/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof _appRoute
    }
    '/_app/ref': {
      id: '/_app/ref'
      path: '/ref'
      fullPath: '/ref'
      preLoaderRoute: typeof RefRouteImport
      parentRoute: typeof _appRoute
    }
    '/health-check': {
      id: '/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _appRoute: _appRoute._addFileChildren(_appRouteChildren),
  HealthCheckRoute: HealthCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
